[package]
name = "asio_wdm_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
asio-sys = "0.2"
anyhow = "1.0"
wasapi = "0.22.0"
windows = "0.62.2"
rubato = "1.0.0"
audioadapter-buffers = "2.0.0"
rtrb = "0.3.2"
